#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int marubatsuanim = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_launcher_background = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int activity_horizontal_margin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int activity_vertical_margin = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int fab_margin = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int nav_header_height = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int nav_header_vertical_spacing = 2130903044;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int baseline_delete_white_48 = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int baseline_developer_mode_24 = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int baseline_developer_mode_black_48 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int baseline_list_24 = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int baseline_list_white_18 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int baseline_list_white_24 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int baseline_list_white_36 = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int baseline_list_white_48 = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int baseline_timeline_24 = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int baseline_timeline_white_24 = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int batsu = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int empty = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ic_menu_camera = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int ic_menu_gallery = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int ic_menu_manage = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int ic_menu_send = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int ic_menu_share = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int ic_menu_slideshow = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int maru = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int round_add_white_48 = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int side_nav_bar = 2130968596;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int button_jsonexport = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int button_jsonimport = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int deleteword = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int description = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int description_removal = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int description_textfield = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int drawer_layout = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int fab = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int genre_textfield = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int imageView = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int jsonenter_textview = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int linearLayout1 = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int list_view = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int maintitle = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int maintitle_removal = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int main_content_Layout = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int nav_devoption = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int nav_quiz = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int nav_settings = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int nav_share = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int nav_test = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int nav_view = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int nav_wordlist = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int quiz_answer = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int quiz_checkanewer = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int quiz_marubatsu = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int quiz_question = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int radioButton_removal = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int registerdialog_title = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int relativeLayout1 = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int scoreanalytics_chartView = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int scoreanalytics_recyclerView = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int scoreanalytics_title = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int settings_erashow = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int settings_marubatsuanimation = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int settings_removealldata = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int settings_removeanswer = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int settings_textView1 = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int settings_textView2 = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int settings_textView3 = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int textView = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int textView1 = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int textView2 = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int title_textfield = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int toolbar = 2131034157;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_main = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_bar_main = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int content_main = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int devoption = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int dialog_directjson = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int dialog_genre = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int dialog_wordenter = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int nav_header_main = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int quiz = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int recyclerview_element = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int recyclerview_element_removal = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int recycler_view = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int scoreanalytics = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int settings = 2131099661;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int activity_main_drawer = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int menu_deleteword = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int menu_main = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int ic_launcher = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int ic_launcher_foreground = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int ic_launcher_round = 2131230722;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int action_settings = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int app_version = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int devoption_import = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int dialog_cancel = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int dialog_delele = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int dialog_deletealldata = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int dialog_deleteelements = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int dialog_notestdata_desc = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int dialog_notestdata_title = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int dialog_notselect_desc = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int dialog_notselect_title = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int dialog_nowords_desc = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int dialog_nowords_title = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int dialog_register = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int navigation_drawer_close = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int navigation_drawer_open = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int quiz_checkanswer = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int quiz_next = 2131296274;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int AppTheme_AppBarOverlay = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int AppTheme_NoActionBar = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int AppTheme_PopupOverlay = 2131361795;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
